/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "app.h"
//#include "stm32f103x.h"

#define HIGH 1
#define LOW 0
#define LED_ON() 			io_set_out(IO_TEST_LED, HIGH)
#define LED_OFF() 			io_set_out(IO_TEST_LED, LOW)
#define LED_TOGGLE()        io_toggle(IO_TEST_LED)

#define GPIO_PIN_SET		1
#define GPIO_PIN_RESET		0




void set_msp(uint32_t msp_value);
int main(void)
{

	mcu_init();

	/* Loop forever */
	while(1)
	{
		if (io_get_in(PUSH_BUTTON) == GPIO_PIN_RESET)
		{
			bl_read_uart_data();
			delay(100);
		}
		else
		{
			uint32_t user_app_address = (uint32_t)USER_APP_FLASH_BASE_ADDR;
			jump_to_user_app(user_app_address);
		}
	}
}


